aravindnc/mongoose-paginate-v2

- src/index.js
This change makes the countDocuments() query bullet proof against invalid arguments and doesn`t throw non-helpful errors.
I followed the official documentation to validate the properties on countDocuments() query:
> https://docs.mongodb.com/manual/reference/method/db.collection.countDocuments/
> Improve countDocuments query

- README.md
- package.json
- src/index.js
Hi 😃 
New feature supports `.read(pref, tags)` for load balancing.
```js
const options: any = {
lean: true,
limit: 10,
offset: 0,
page: 1,
populate: ['images', 'comments'],
read: {
pref: 'secondary'
}
};
const articles = await Article.paginate({}, options);
res.send(articles);
```
ref: https://github.com/Automattic/mongoose/blob/master/lib/query.js#L1008
```js
/**
* Determines the MongoDB nodes from which to read.
* @param pref one of the listed preference options or aliases
* @tags optional tags for this query
*/
read(pref: string, tags?: any[]): this;
```
Regards.
> Supports determines the MongoDB nodes from which to read.

- src/index.js
- tests/index.js
Hello everyone, thank you for the great library.
Bug has been introduced in this commit: https://github.com/aravindnc/mongoose-paginate-v2/commit/2a2a70e4b6d12c6317e830c68816ee7c90bf27fd#diff-1fdf421c05c1140f6d71444ea2b27638R188
If we provide option `page` and not `offset` then this condition is always `true`:
```
} else if (page == 1 && offset !== 0) {
meta[labelHasPrevPage] = true;
```
As a result we have `prevPage` on a first page if we use `page` option.
To solve: we need to check if offset is defined before compare to 0
This PR would:
- fix the bug
- add a test case for a first page
> Fix first page bug with page

- .travis.yml
- tests/index.js
It would be nice to use a CI tool to execute tests automatically on PR etc.
I suggest https://travis-ci.com/ - it's free for open source.
@aravindnc if you accept this request, you will need to add project at https://travis-ci.com/ after merge. And maybe put badges into README.md ;) 
Tests by Travis will be executed on the next commit after `.travis.yml` is added to the project.
This PR would:
- add `.travis.yml` to execute tests for node versions `latest`/`lts`/`10`/`9`/`8`
- add test case for a last page (a test opposite to https://github.com/aravindnc/mongoose-paginate-v2/pull/67)
- add `useUnifiedTopology: true` to `mongo.connect` in tests to avoid warning about deprecation.
> Add travis ci

- README.md
Hi,
Thanks for the great lib. Just wanted to point out that the `options` option isn't documented, but it's quite useful for places where you need to add options to the `find()` query.
Re: mongodb-js/mongoose-autopopulate#67
> docs: document the `options` option

- .eslintrc.js
- .prettierrc
- CODE_OF_CONDUCT.md
- README.md
- package-lock.json
- package.json
- src/index.js
- tests/index.js
> Add eslint and prettier with git hooks integration

- src/index.js
Fix to issue #124 where the app crashes when a page option of 0 or less is passed.
> Fix for page options less than 1

- src/index.js
- tests/index.js
Revert for part of 277d3f3af4e58f5f0daa53dde661aa3a5624d9e4
The fix for issue #119 would be to set offset to 0 or do not pass it anyways.
@serjmac will lose the first record in the list on every query.
That's why hasPrevPage is correctly set to true.
I rely on the existing behaviour because if a user changes the number of elements per page (limit e.g. 5 > 10) and was already on page 2 of the previous query (e.g. offset 5) he needs to be able to go back to the complete page 1 starting at record 0.
> Fix hasPrevPage behaviour with limit > offset > 0

- README.md
When I first used the library I had no idea where "PaginateModel" was coming from and had to look in an issue from the library to find out. This change will make it clear that it's coming from mongoose.
> docs: add mongoose import to typescript example

- README.md
- index.d.ts
- src/index.js
- tests/index.js
Add a new feature for sub-document pagination #174
> feat: add sub-document pagination (feats: #174)

- README.md
- src/index.js
Add `customFind` options to accept find method to use other than the mongoose's `find`. This will close #38
> Add customFind options

- src/index.js
Based on the documentation
> If pagination is set to false, it will return all docs without adding limit condition  
When we set pagination is `false` we do expect to all documents are returned, we can simply use the length of docs as countDocuments is considered costly in general
```
yarn test
yarn run v1.22.19
$ npm run build
> mongoose-paginate-v2@1.7.1 build
> babel src -d dist
Successfully compiled 3 files with Babel (226ms).
$ ./node_modules/.bin/mocha tests/*.js -R spec --ui bdd --timeout 9999999
mongoose-paginate
(node:7214) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
✓ promise return test
✓ callback test
✓ with page and limit
✓ first page with page and limit, limit …
```
> fix: when pagination is false, skip the execution of count

- src/pagination-parameters.js
As described [here](https://github.com/aravindnc/mongoose-paginate-v2#zero-limit), `limit` should be able to be set to 0.
At the moment, when executing `new PaginationParameters({ query: { limit: 0 } }).getOptions()` result is `{}`. 
My patch will have it to return `{ limit: 0 }`.
> fix: set limit when limit is 0

- index.d.ts
Sequel to [this comment](https://github.com/aravindnc/mongoose-paginate-v2/issues/162#issuecomment-1721506125) in #162 
This PR aims to type the items in the `docs` field returned from calling the `paginate` function.
It uses [TypeScript function overloads](https://www.typescriptlang.org/docs/handbook/2/functions.html#function-overloads) to achieve this
> set dynamic type for `docs` items

- index.d.ts
- package-lock.json
- package.json
- src/index.js
- src/pagination-subdocs.js
- tests/index.js
Here is my attempt to add support to Mongoose v8 to this package. The changes here are solely related to the mongoose migration guides:
- [v5 to v6](https://mongoosejs.com/docs/migrating_to_6.html):
- [mongoose.connect() returns a Promise](https://mongoosejs.com/docs/migrating_to_6.html#mongoose-connect-returns-a-promise)
- [No More Deprecation Warning Options](https://mongoosejs.com/docs/migrating_to_6.html#no-more-deprecation-warning-options)
- [v6 to v7](https://mongoosejs.com/docs/migrating_to_7.html):
- [Dropped callback support](https://mongoosejs.com/docs/migrating_to_7.html#dropped-callback-support)
- [Removed LeanDocument and support for extends Document](https://mongoosejs.com/docs/migrating_to_7.html#removed-leandocument-and-support-for-extends-document)
- [v7 to …
> Upgrade to mongoose v8

- src/pagination-subdocs.js
- set count after result was populated (in case we have match filter etc)
> fix: subdocs pagination count

- src/index.js
MongoDB < 3.4 is only supported by mongoose 5 or below
In mongoose 5, `Model.countDocument`'s signature is `Model.countDocuments = function countDocuments(conditions, callback) {...}`. 
```js
/**
* Counts number of documents matching `filter` in a database collection.
*
* ####Example:
*
*     Adventure.countDocuments({ type: 'jungle' }, function (err, count) {
*       console.log('there are %d jungle adventures', count);
*     });
*
* If you want to count all documents in a large collection,
* use the [`estimatedDocumentCount()` function](/docs/api.html#model_Model.estimatedDocumentCount)
* instead. If you call `countDocuments({})`, MongoDB will always execute
* a full collection scan and **not** use any indexes.
*
* The `countDocuments()` function is similar to `count()`, but there are a …
```
> MongoDB < 3.4: Fix for countDocument

- index.d.ts
> fix: correct `PaginateDocument` type parameters and merge `PaginateModel` interface

- index.d.ts
#218 is a likely cause of #232 (and Automattic/mongoose#15423). In TypeScript 5, module augmentation generics need to be exactly identical, including default values and names. This PR makes it so that `interface Query`'s generics line up with Mongoose 8.9.3+.
Unfortunately can't make it line up exactly because Mongoose made some changes to `class Query` generics in 8.6.0 and 8.9.3 because we weren't aware that anyone was using module augmentation with Query. TBH we didn't even know you could use module augmentation with classes :face_with_diagonal_mouth: . Mongoose will keep this interface consistent in 8.x.
> make Query interface generics consistent with Mongoose 8.15 re: #218

- index.d.ts
This PR fixes a type definition inconsistency where the `offset` field in `PaginateResult` interface was marked as required, but the actual implementation only returns `offset` when explicitly provided in options.
When using page-based pagination (without explicit offset), the runtime behavior doesn't include an `offset` field in the result, causing TypeScript type mismatches.
- Changed `offset: number` to `offset?: number | undefined` in the `PaginateResult<T>` interface
- This aligns the TypeScript types with the actual runtime behavior
This is a non-breaking change that only makes the type definition more accurate. All existing code will continue to work as expected.
> fix: make offset field optional in PaginateResult type definition

- src/index.js
Currently if I want to remove some fields from the output, I can't do it directly in the options. This fix make so if someone sets the customLabels in this way:
```
{
totalDocs: 'total',
docs: 'data',
limit: null,
page: null,
totalPages: null,
nextPage: null,
prevPage: null,
pagingCounter: null,
hasPrevPage: null,
hasNextPage: null,
meta: null,
}
```
Gets an output like this:
```
{
total: 20,
data: []
}
```
And not like this:
```
{
total: 20,
data: [],
null: 1
}
```
> fix: Do not set nulled/removed custom labels
